services:
  speedcubing-bot:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - INSTANCE_NAME=${INSTANCE_NAME}
    restart: unless-stopped 